# Generated by Django 5.2.16 on 2026-07-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="campaignmap",
            new_name="maps_campai_campaig_267d5d_idx",
            old_name="maps_campai_campaig_a103ab_idx",
        ),
        migrations.RenameIndex(
            model_name="campaignmap",
            new_name="maps_campai_campaig_d7d1c7_idx",
            old_name="maps_campai_campaig_013320_idx",
        ),
    ]
