# Generated by Django 5.2.16 on 2026-07-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ship",
            new_name="ships_ship_campaig_7859b9_idx",
            old_name="ships_ship_campaig_6f18bc_idx",
        ),
    ]
