# Generated by Django 5.2.16 on 2026-07-18 18:28

from django.db import migrations, models


def mark_existing_active_ships_as_crew(apps, schema_editor):
    Ship = apps.get_model('ships', 'Ship')
    Ship.objects.filter(is_active=True).update(belongs_to_crew=True)


def unmark_crew_ships(apps, schema_editor):
    Ship = apps.get_model('ships', 'Ship')
    Ship.objects.update(belongs_to_crew=False)


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('ships', '0002_rename_ships_ship_campaig_6f18bc_idx_ships_ship_campaig_7859b9_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ship',
            options={'ordering': ('-belongs_to_crew', '-is_active', '-updated_at')},
        ),
        migrations.RemoveConstraint(
            model_name='ship',
            name='one_active_ship_per_campaign',
        ),
        migrations.RemoveIndex(
            model_name='ship',
            name='ships_ship_campaig_7859b9_idx',
        ),
        migrations.AddField(
            model_name='ship',
            name='belongs_to_crew',
            field=models.BooleanField(db_index=True, default=False, verbose_name='pertence à tripulação'),
        ),
        migrations.RunPython(mark_existing_active_ships_as_crew, unmark_crew_ships),
        migrations.AddIndex(
            model_name='ship',
            index=models.Index(fields=['campaign', 'is_active', 'belongs_to_crew'], name='ships_ship_campaig_4936e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='ship',
            constraint=models.UniqueConstraint(condition=models.Q(('belongs_to_crew', True), ('is_active', True)), fields=('campaign',), name='one_crew_ship_per_campaign'),
        ),
    ]
