# Generated by Django 5.2.16 on 2026-07-29 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0003_alter_ship_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="ships/images/", verbose_name="imagem"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="ships.ship",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "pk"),
            },
        ),
    ]
