# Generated by Django 5.2.16 on 2026-07-31

import ships.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0004_shipimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="ships/images/",
                validators=[ships.validators.validate_ship_image],
                verbose_name="imagem",
            ),
        ),
        migrations.AlterField(
            model_name="shipimage",
            name="image",
            field=models.ImageField(
                upload_to="ships/images/",
                validators=[ships.validators.validate_ship_image],
                verbose_name="imagem",
            ),
        ),
    ]
