# Generated by Django 5.2.16 on 2026-07-17 14:17

import django.core.validators
import django.db.models.deletion
import enemies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enemy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nome")),
                ("slug", models.SlugField(unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=enemies.models.enemy_image_path,
                        validators=[enemies.models.validate_enemy_image],
                        verbose_name="imagem",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("minion", "Lacaio"),
                            ("standard", "Comum"),
                            ("elite", "Elite"),
                            ("boss", "Chefe"),
                            ("creature", "Criatura"),
                            ("vehicle", "Veículo"),
                            ("special", "Especial"),
                        ],
                        db_index=True,
                        default="standard",
                        max_length=20,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("any", "Qualquer"),
                            ("urban", "Urbano"),
                            ("forest", "Floresta"),
                            ("desert", "Deserto"),
                            ("mountain", "Montanha"),
                            ("sea", "Mar"),
                            ("ship", "Navio"),
                            ("island", "Ilha"),
                            ("underground", "Subterrâneo"),
                            ("special", "Especial"),
                        ],
                        db_index=True,
                        default="any",
                        max_length=20,
                        verbose_name="ambiente",
                    ),
                ),
                (
                    "difficulty_tier",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="faixa de dificuldade"
                    ),
                ),
                (
                    "challenge_rating",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=6, verbose_name="ND"
                    ),
                ),
                (
                    "recommended_min_level",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="nível mínimo"
                    ),
                ),
                (
                    "recommended_max_level",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="nível máximo"
                    ),
                ),
                (
                    "max_hp",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="PV máximo",
                    ),
                ),
                (
                    "armor_class",
                    models.PositiveSmallIntegerField(default=10, verbose_name="CR"),
                ),
                (
                    "resistance_bonus",
                    models.SmallIntegerField(default=0, verbose_name="resistência"),
                ),
                (
                    "initiative",
                    models.SmallIntegerField(default=0, verbose_name="iniciativa"),
                ),
                (
                    "movement",
                    models.PositiveSmallIntegerField(
                        default=9, verbose_name="deslocamento"
                    ),
                ),
                (
                    "strength",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "dexterity",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "constitution",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "intelligence",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "wisdom",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "charisma",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "is_boss",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="chefe"
                    ),
                ),
                (
                    "is_named_character",
                    models.BooleanField(
                        default=False, verbose_name="personagem nomeado"
                    ),
                ),
                (
                    "is_canon_character",
                    models.BooleanField(
                        default=False, verbose_name="personagem canônico"
                    ),
                ),
                (
                    "operational_complexity",
                    models.CharField(
                        choices=[
                            ("simple", "Simples"),
                            ("moderate", "Moderado"),
                            ("complex", "Complexo"),
                        ],
                        db_index=True,
                        default="simple",
                        max_length=20,
                        verbose_name="complexidade",
                    ),
                ),
                (
                    "encounter_mode",
                    models.CharField(
                        choices=[
                            ("normal", "Confronto normal"),
                            ("reduced", "Versão reduzida"),
                            ("narrative", "Encontro narrativo"),
                            ("not_recommended", "Não recomendado"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=20,
                        verbose_name="modo de encontro",
                    ),
                ),
                (
                    "threat_score_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="ameaça manual",
                    ),
                ),
                (
                    "is_available_for_generator",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="disponível no gerador",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="ativo"
                    ),
                ),
                (
                    "combat_behavior",
                    models.TextField(blank=True, verbose_name="comportamento"),
                ),
                (
                    "retreat_condition",
                    models.TextField(blank=True, verbose_name="condição de fuga"),
                ),
                (
                    "surrender_condition",
                    models.TextField(blank=True, verbose_name="condição de rendição"),
                ),
                (
                    "master_tips",
                    models.TextField(blank=True, verbose_name="dicas ao mestre"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas privadas")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="EnemyFaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="EnemyAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nome")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("action", "Ação"),
                            ("bonus_action", "Ação bônus"),
                            ("reaction", "Reação"),
                            ("passive", "Passiva"),
                            ("legendary", "Especial"),
                            ("other", "Outra"),
                        ],
                        default="action",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("attack_bonus", models.SmallIntegerField(blank=True, null=True)),
                ("save_dc", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("save_attribute", models.CharField(blank=True, max_length=20)),
                ("range_text", models.CharField(blank=True, max_length=100)),
                ("target_text", models.CharField(blank=True, max_length=100)),
                ("damage_text", models.CharField(blank=True, max_length=150)),
                ("effect_text", models.TextField(blank=True)),
                ("resource_cost", models.CharField(blank=True, max_length=100)),
                ("recharge_text", models.CharField(blank=True, max_length=100)),
                ("is_limited", models.BooleanField(default=False)),
                (
                    "uses_per_encounter",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enemy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="enemies.enemy",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.AddField(
            model_name="enemy",
            name="faction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enemies",
                to="enemies.enemyfaction",
            ),
        ),
        migrations.CreateModel(
            name="EnemyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("feature_type", models.CharField(blank=True, max_length=50)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "enemy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="enemies.enemy",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.AddConstraint(
            model_name="enemy",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_hp__gt", 0)), name="enemy_max_hp_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="enemy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recommended_max_level__gte", models.F("recommended_min_level"))
                ),
                name="enemy_level_range_valid",
            ),
        ),
    ]
