# Generated by Django 5.2.16 on 2026-07-17 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        (
            "characters",
            "0001_initial",
        ),
        ("enemies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Fácil"),
                            ("medium", "Médio"),
                            ("hard", "Difícil"),
                        ],
                        max_length=10,
                        verbose_name="dificuldade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("ready", "Preparado"),
                            ("started", "Iniciado"),
                            ("finished", "Finalizado"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "has_boss",
                    models.BooleanField(default=False, verbose_name="com chefe"),
                ),
                (
                    "environment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("any", "Qualquer"),
                            ("urban", "Urbano"),
                            ("forest", "Floresta"),
                            ("desert", "Deserto"),
                            ("mountain", "Montanha"),
                            ("sea", "Mar"),
                            ("ship", "Navio"),
                            ("island", "Ilha"),
                            ("underground", "Subterrâneo"),
                            ("special", "Especial"),
                        ],
                        max_length=20,
                        verbose_name="ambiente",
                    ),
                ),
                (
                    "estimated_difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easy", "Fácil"),
                            ("medium", "Médio"),
                            ("hard", "Difícil"),
                        ],
                        max_length=10,
                        verbose_name="estimativa de dificuldade",
                    ),
                ),
                (
                    "estimated_threat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("operational_load", models.PositiveIntegerField(default=0)),
                (
                    "generator_notes",
                    models.TextField(blank=True, verbose_name="alertas do gerador"),
                ),
                (
                    "master_notes",
                    models.TextField(blank=True, verbose_name="notas do mestre"),
                ),
                ("generation_parameters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_encounters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters",
                        to="enemies.enemyfaction",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EncounterEnemy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=150)),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_hp_override",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "armor_class_override",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "resistance_bonus_override",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("is_boss", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("master_note", models.TextField(blank=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enemy_groups",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "enemy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounter_groups",
                        to="enemies.enemy",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="EncounterParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounter_participations",
                        to="characters.character",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="encounters.encounter",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["campaign", "status"], name="encounters__campaig_3f10c4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="encounterparticipant",
            constraint=models.UniqueConstraint(
                fields=("encounter", "character"), name="unique_encounter_participant"
            ),
        ),
    ]
