from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import characters.validators
class Migration(migrations.Migration):
 initial=True
 dependencies=[('campaigns','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='Character',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('name',models.CharField(max_length=150)),('portrait',models.ImageField(blank=True,upload_to=characters.validators.portrait_upload,validators=[characters.validators.validate_image])),('level',models.PositiveSmallIntegerField(default=1,validators=[django.core.validators.MinValueValidator(1),django.core.validators.MaxValueValidator(20)])),('species',models.CharField(blank=True,max_length=100)),('profession',models.CharField(blank=True,max_length=100)),('combat_style',models.CharField(blank=True,max_length=150)),('background',models.CharField(blank=True,max_length=150)),('bounty',models.PositiveBigIntegerField(default=0)),('armor_class',models.PositiveSmallIntegerField(default=10)),('proficiency_bonus',models.SmallIntegerField(default=2)),('initiative',models.SmallIntegerField(default=0)),('movement',models.PositiveSmallIntegerField(default=9)),('max_hp',models.PositiveIntegerField(default=1)),('current_hp',models.PositiveIntegerField(default=1)),('max_power_points',models.PositiveIntegerField(default=0)),('current_power_points',models.PositiveIntegerField(default=0)),*[(x,models.PositiveSmallIntegerField(default=10,validators=[django.core.validators.MinValueValidator(1),django.core.validators.MaxValueValidator(30)])) for x in ('strength','dexterity','constitution','intelligence','wisdom','charisma')],('haki_declared',models.BooleanField(default=False)),('haki_trained',models.BooleanField(default=False)),('devil_fruit_name',models.CharField(blank=True,default='',max_length=150)),('devil_fruit_available',models.BooleanField(default=False)),('appearance',models.TextField(blank=True)),('personality',models.TextField(blank=True)),('dream',models.TextField(blank=True)),('notes',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('campaign',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='characters',to='campaigns.campaign')),('user',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='characters',to=settings.AUTH_USER_MODEL))],options={'ordering':('name',),'constraints':[models.UniqueConstraint(fields=('campaign','user'),name='unique_character_per_campaign_user')],'indexes':[models.Index(fields=['campaign','user'],name='characters__campaig_773e62_idx')]}),
  migrations.CreateModel(name='Skill',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('name',models.CharField(max_length=100)),('slug',models.SlugField(unique=True)),('related_attribute',models.CharField(choices=[(x,x.title()) for x in ('strength','dexterity','constitution','intelligence','wisdom','charisma')],max_length=20)),('description',models.TextField(blank=True)),('sort_order',models.PositiveSmallIntegerField(default=0)),('is_active',models.BooleanField(db_index=True,default=True))],options={'ordering':('sort_order','name')}),
  migrations.CreateModel(name='CharacterCondition',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('name',models.CharField(max_length=100)),('description',models.TextField(blank=True)),('is_active',models.BooleanField(db_index=True,default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('character',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='conditions',to='characters.character'))],options={'ordering':('-created_at',)}),
  migrations.CreateModel(name='CharacterFeature',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('name',models.CharField(max_length=150)),('description',models.TextField(blank=True)),('source',models.CharField(blank=True,max_length=100)),('is_available',models.BooleanField(default=True)),('sort_order',models.PositiveSmallIntegerField(default=0)),('character',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='features',to='characters.character'))],options={'ordering':('sort_order','name')}),
  migrations.CreateModel(name='CharacterTechnique',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('name',models.CharField(max_length=150)),('description',models.TextField(blank=True)),('action_type',models.CharField(choices=[('action','Ação'),('bonus_action','Ação bônus'),('reaction','Reação'),('passive','Passiva'),('other','Outro')],default='action',max_length=20)),('range_text',models.CharField(blank=True,max_length=100)),('damage_text',models.CharField(blank=True,max_length=150)),('cost',models.CharField(blank=True,max_length=100)),('is_available',models.BooleanField(default=True)),('is_featured',models.BooleanField(default=False)),('sort_order',models.PositiveSmallIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('character',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='techniques',to='characters.character'))],options={'ordering':('sort_order','name')}),
  migrations.CreateModel(name='CharacterSkill',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('is_proficient',models.BooleanField(default=False)),('is_expert',models.BooleanField(default=False)),('custom_bonus',models.SmallIntegerField(blank=True,null=True)),('character',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='skills',to='characters.character')),('skill',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='characters.skill'))],options={'constraints':[models.UniqueConstraint(fields=('character','skill'),name='unique_character_skill')]}),]
