# Generated by Django 5.2.16 on 2026-07-17 15:39

import characters.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="character",
            new_name="characters__campaig_ad3c95_idx",
            old_name="characters__campaig_773e62_idx",
        ),
        migrations.AlterField(
            model_name="character",
            name="appearance",
            field=models.TextField(blank=True, verbose_name="aparência"),
        ),
        migrations.AlterField(
            model_name="character",
            name="armor_class",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="CR"),
        ),
        migrations.AlterField(
            model_name="character",
            name="background",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="antecedente"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="bounty",
            field=models.PositiveBigIntegerField(default=0, verbose_name="recompensa"),
        ),
        migrations.AlterField(
            model_name="character",
            name="charisma",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="carisma",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="combat_style",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="estilo de combate"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="constitution",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="constituição",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="current_hp",
            field=models.PositiveIntegerField(default=1, verbose_name="PV atual"),
        ),
        migrations.AlterField(
            model_name="character",
            name="current_power_points",
            field=models.PositiveIntegerField(default=0, verbose_name="PP atual"),
        ),
        migrations.AlterField(
            model_name="character",
            name="devil_fruit_available",
            field=models.BooleanField(
                default=False, verbose_name="Akuma no Mi disponível"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="devil_fruit_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Akuma no Mi"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="dexterity",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="destreza",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="dream",
            field=models.TextField(blank=True, verbose_name="sonho"),
        ),
        migrations.AlterField(
            model_name="character",
            name="haki_declared",
            field=models.BooleanField(default=False, verbose_name="Haki declarado"),
        ),
        migrations.AlterField(
            model_name="character",
            name="haki_trained",
            field=models.BooleanField(default=False, verbose_name="Haki treinado"),
        ),
        migrations.AlterField(
            model_name="character",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="initiative",
            field=models.SmallIntegerField(default=0, verbose_name="iniciativa"),
        ),
        migrations.AlterField(
            model_name="character",
            name="intelligence",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="inteligência",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="nível",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="max_hp",
            field=models.PositiveIntegerField(default=1, verbose_name="PV máximo"),
        ),
        migrations.AlterField(
            model_name="character",
            name="max_power_points",
            field=models.PositiveIntegerField(default=0, verbose_name="PP máximo"),
        ),
        migrations.AlterField(
            model_name="character",
            name="movement",
            field=models.PositiveSmallIntegerField(
                default=9, verbose_name="deslocamento"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(max_length=150, verbose_name="nome"),
        ),
        migrations.AlterField(
            model_name="character",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notas"),
        ),
        migrations.AlterField(
            model_name="character",
            name="personality",
            field=models.TextField(blank=True, verbose_name="personalidade"),
        ),
        migrations.AlterField(
            model_name="character",
            name="portrait",
            field=models.ImageField(
                blank=True,
                upload_to=characters.validators.portrait_upload,
                validators=[characters.validators.validate_image],
                verbose_name="retrato",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="profession",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="profissão"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="proficiency_bonus",
            field=models.SmallIntegerField(default=2, verbose_name="proficiência"),
        ),
        migrations.AlterField(
            model_name="character",
            name="species",
            field=models.CharField(blank=True, max_length=100, verbose_name="espécie"),
        ),
        migrations.AlterField(
            model_name="character",
            name="strength",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="força",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="wisdom",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="sabedoria",
            ),
        ),
        migrations.AlterField(
            model_name="charactercondition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="characterfeature",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="characterskill",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="charactertechnique",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
