# Generated by Django 5.2.16 on 2026-07-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_presence_character_willpower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercreation',
            name='attribute_method',
            field=models.CharField(choices=[('point_distribution', 'Distribuição por pontos'), ('standard_array', 'Conjunto padrão'), ('random_4d6_drop_lowest', 'Aleatório 4d6')], default='point_distribution', max_length=30),
        ),
    ]
