# Generated by Django 5.2.16 on 2026-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_charactercreation_attribute_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='idade'),
        ),
        migrations.AddField(
            model_name='character',
            name='dream_path',
            field=models.CharField(blank=True, choices=[('knowledge_companionship', 'Conhecimento pelo Companheirismo (C/C)'), ('freedom_companionship', 'Liberdade pelo Companheirismo (L/C)'), ('power_companionship', 'Poder pelo Companheirismo (P/C)'), ('knowledge_strength', 'Conhecimento pela Força (C/F)'), ('freedom_strength', 'Liberdade pela Força (L/F)'), ('power_strength', 'Poder pela Força (P/F)'), ('knowledge_deception', 'Conhecimento pela Enganação (C/E)'), ('freedom_deception', 'Liberdade pela Enganação (L/E)'), ('power_deception', 'Poder pela Enganação (P/E)')], default='', max_length=40, verbose_name='caminho'),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='altura'),
        ),
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='peso'),
        ),
        migrations.AddField(
            model_name='charactercreation',
            name='age',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='charactercreation',
            name='dream_path',
            field=models.CharField(blank=True, choices=[('knowledge_companionship', 'Conhecimento pelo Companheirismo (C/C)'), ('freedom_companionship', 'Liberdade pelo Companheirismo (L/C)'), ('power_companionship', 'Poder pelo Companheirismo (P/C)'), ('knowledge_strength', 'Conhecimento pela Força (C/F)'), ('freedom_strength', 'Liberdade pela Força (L/F)'), ('power_strength', 'Poder pela Força (P/F)'), ('knowledge_deception', 'Conhecimento pela Enganação (C/E)'), ('freedom_deception', 'Liberdade pela Enganação (L/E)'), ('power_deception', 'Poder pela Enganação (P/E)')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='charactercreation',
            name='height',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='charactercreation',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
