# Generated by Django 5.2.16 on 2026-07-20 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_age_character_dream_path_character_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertechnique',
            name='attribute_modifier',
            field=models.CharField(choices=[('strength', 'Força'), ('dexterity', 'Destreza'), ('constitution', 'Constituição'), ('wisdom', 'Sabedoria'), ('willpower', 'Vontade'), ('presence', 'Presença')], default='strength', max_length=20, verbose_name='modificador de atributo'),
        ),
        migrations.AddField(
            model_name='charactertechnique',
            name='category',
            field=models.CharField(choices=[('attack', 'Ataque'), ('support', 'Suporte')], default='attack', max_length=20, verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='charactertechnique',
            name='damage_die',
            field=models.CharField(blank=True, max_length=40, verbose_name='dado de dano/cura'),
        ),
        migrations.AddField(
            model_name='charactertechnique',
            name='power_points_cost',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='PP para uso'),
        ),
        migrations.AddField(
            model_name='charactertechnique',
            name='required_weapon_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='tipo de arma requerida'),
        ),
        migrations.AddField(
            model_name='charactertechnique',
            name='technique_type',
            field=models.CharField(choices=[('unarmed', 'Desarmado'), ('basic', 'Básico'), ('innate', 'Técnica inata'), ('combat', 'Técnica de combate'), ('buff', 'Buff'), ('heal', 'Cura')], default='innate', max_length=20, verbose_name='tipo de técnica'),
        ),
        migrations.CreateModel(
            name='CharacterWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('range_text', models.CharField(blank=True, max_length=100, verbose_name='alcance')),
                ('damage_die', models.CharField(blank=True, max_length=40, verbose_name='dado de dano')),
                ('attribute_modifier', models.CharField(choices=[('strength', 'Força'), ('dexterity', 'Destreza'), ('constitution', 'Constituição'), ('wisdom', 'Sabedoria'), ('willpower', 'Vontade'), ('presence', 'Presença')], default='strength', max_length=20, verbose_name='modificador de atributo')),
                ('weapon_type', models.CharField(max_length=100, verbose_name='tipo da arma')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='disponível')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='characters.character')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['character', 'is_available', 'weapon_type'], name='characters__charact_bb9a0b_idx')],
            },
        ),
    ]
