# Generated by Django 5.2.16 on 2026-07-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_charactertechnique_attribute_modifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactertechnique',
            name='cost',
        ),
    ]
