# Generated by Django 5.2.16 on 2026-07-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_remove_charactertechnique_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterweapon',
            name='is_proficient',
            field=models.BooleanField(default=False, verbose_name='proficiente'),
        ),
    ]
