# Generated by Django 5.2.16 on 2026-07-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_characterweapon_is_proficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactertechnique',
            name='technique_type',
            field=models.CharField(choices=[('unarmed', 'Desarmado'), ('basic', 'Básico'), ('innate', 'Técnica inata'), ('combat', 'Técnica com arma'), ('buff', 'Buff'), ('heal', 'Cura')], default='innate', max_length=20, verbose_name='tipo de técnica'),
        ),
    ]
