# Generated by Django 5.2.16 on 2026-08-31 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_character_money'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='characterfeature',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_character_features', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characterfeature',
            name='source_type',
            field=models.CharField(choices=[('system', 'Sistema'), ('character_creation', 'Criação'), ('level_up', 'Passagem de nível'), ('master', 'Mestre'), ('player', 'Jogador'), ('legacy', 'Legado')], db_index=True, default='legacy', max_length=30, verbose_name='origem'),
        ),
        migrations.AddField(
            model_name='charactertechnique',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_character_techniques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charactertechnique',
            name='source_type',
            field=models.CharField(choices=[('system', 'Sistema'), ('character_creation', 'Criação'), ('level_up', 'Passagem de nível'), ('master', 'Mestre'), ('player', 'Jogador'), ('legacy', 'Legado')], db_index=True, default='legacy', max_length=30, verbose_name='origem'),
        ),
        migrations.AddField(
            model_name='characterweapon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_character_weapons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characterweapon',
            name='source_type',
            field=models.CharField(choices=[('system', 'Sistema'), ('character_creation', 'Criação'), ('level_up', 'Passagem de nível'), ('master', 'Mestre'), ('player', 'Jogador'), ('legacy', 'Legado')], db_index=True, default='legacy', max_length=30, verbose_name='origem'),
        ),
        migrations.CreateModel(
            name='CharacterChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('object_type', models.CharField(db_index=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='characters.character')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['character', '-created_at'], name='characters__charact_4f4873_idx'), models.Index(fields=['action', 'object_type'], name='characters__action_606c1d_idx')],
            },
        ),
    ]
