# Generated by Django 5.2.16 on 2026-08-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_characterfeature_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterfeature',
            name='level_acquired',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='nível adquirido'),
        ),
        migrations.AddField(
            model_name='characterlevelup',
            name='draft_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='characterlevelup',
            name='draft_techniques',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='characterlevelup',
            name='hp_gain_total',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterlevelup',
            name='hp_method',
            field=models.CharField(choices=[('average', 'Valor médio'), ('rolled', 'Rolado')], default='average', max_length=20),
        ),
        migrations.AddField(
            model_name='characterlevelup',
            name='hp_roll_result',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characterleveluphistory',
            name='created_features',
            field=models.ManyToManyField(blank=True, related_name='level_up_history_entries', to='characters.characterfeature'),
        ),
        migrations.AddField(
            model_name='characterleveluphistory',
            name='created_techniques',
            field=models.ManyToManyField(blank=True, related_name='level_up_history_entries', to='characters.charactertechnique'),
        ),
        migrations.AddField(
            model_name='characterleveluphistory',
            name='hp_gain_total',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterleveluphistory',
            name='hp_method',
            field=models.CharField(choices=[('average', 'Valor médio'), ('rolled', 'Rolado')], default='average', max_length=20),
        ),
        migrations.AddField(
            model_name='characterleveluphistory',
            name='hp_roll_result',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charactertechnique',
            name='level_acquired',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='nível adquirido'),
        ),
        migrations.AddField(
            model_name='charactertechnique',
            name='source',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
