# Generated by Django 5.2.16 on 2026-08-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_characterfeature_level_acquired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='great_damage_recovery_day',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='dia atual da recuperação de grande dano'),
        ),
        migrations.AddField(
            model_name='character',
            name='great_damage_recovery_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='dias de recuperação de grande dano'),
        ),
        migrations.AddField(
            model_name='character',
            name='great_damage_recovery_hp_per_rest',
            field=models.PositiveIntegerField(default=0, verbose_name='PV por descanso da recuperação de grande dano'),
        ),
    ]
