# Generated by Django 5.2.16 on 2026-09-02 21:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_character_great_damage_recovery_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertechnique',
            name='effect_summary',
            field=models.CharField(blank=True, max_length=220, verbose_name='resumo do efeito'),
        ),
        migrations.AddField(
            model_name='charactertechnique',
            name='usage_mode',
            field=models.CharField(choices=[('instant', 'Uso imediato'), ('continuous', 'Efeito contínuo'), ('graded', 'Uso em graus')], db_index=True, default='instant', max_length=20, verbose_name='modalidade de uso'),
        ),
        migrations.CreateModel(
            name='CharacterTechniqueActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('ended', 'Encerrada')], db_index=True, default='active', max_length=12)),
                ('activation_cost', models.PositiveSmallIntegerField(default=0)),
                ('maintenance_cost', models.PositiveSmallIntegerField(default=1)),
                ('rounds_maintained', models.PositiveSmallIntegerField(default=0)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_technique_activations', to=settings.AUTH_USER_MODEL)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='characters.charactertechnique')),
            ],
            options={
                'ordering': ('-activated_at',),
            },
        ),
        migrations.CreateModel(
            name='CharacterTechniqueGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='grau')),
                ('effect_summary', models.CharField(max_length=220, verbose_name='resumo do efeito')),
                ('description', models.TextField(blank=True, verbose_name='descrição complementar')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='characters.charactertechnique')),
            ],
            options={
                'ordering': ('grade',),
            },
        ),
        migrations.CreateModel(
            name='CharacterTechniqueUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('use', 'Uso'), ('activate', 'Ativação'), ('maintain', 'Manutenção')], default='use', max_length=12)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('power_points_spent', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('activation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uses', to='characters.charactertechniqueactivation')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='characters.charactertechnique')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undone_character_technique_uses', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_technique_uses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='charactertechniqueactivation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('technique',), name='unique_active_character_technique'),
        ),
        migrations.AddConstraint(
            model_name='charactertechniquegrade',
            constraint=models.UniqueConstraint(fields=('technique', 'grade'), name='unique_character_technique_grade'),
        ),
        migrations.AddIndex(
            model_name='charactertechniqueuse',
            index=models.Index(fields=['technique', '-created_at'], name='characters__techniq_701d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='charactertechniqueuse',
            index=models.Index(fields=['technique', 'undone_at'], name='characters__techniq_9a83a6_idx'),
        ),
    ]
