# Generated by Django 5.2.16 on 2026-09-19 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_charactertechnique_effect_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDerivedEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('hp_flat', 'PV fixo'), ('hp_per_level', 'PV por nível'), ('cr_bonus', 'Bônus de CR'), ('cr_formula', 'Fórmula de CR')], max_length=30)),
                ('value', models.SmallIntegerField(default=0)),
                ('formula', models.CharField(blank=True, max_length=60)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(max_length=150)),
                ('applied_through_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_effects', to='characters.character')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_effects', to='characters.characterfeature')),
            ],
            options={
                'ordering': ('effect_type', 'id'),
                'indexes': [models.Index(fields=['character', 'effect_type', 'is_active'], name='characters__charact_05f434_idx')],
            },
        ),
    ]
