# Generated by Django 5.2.16 on 2026-09-19 18:18

import characters.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_characterderivedeffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='wanted_poster',
            field=models.ImageField(blank=True, upload_to=characters.validators.wanted_poster_upload, validators=[characters.validators.validate_image], verbose_name='cartaz de procurado'),
        ),
    ]
