# Generated by Django 5.2.16 on 2026-07-17 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inventoryitem",
            new_name="inventory_i_charact_f76f88_idx",
            old_name="inventory_i_charact_8f5b83_idx",
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="description",
            field=models.TextField(blank=True, verbose_name="descrição"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="ativo"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="is_visible",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="visível"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="master_note",
            field=models.TextField(blank=True, verbose_name="nota do mestre"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="name",
            field=models.CharField(max_length=150, verbose_name="nome"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="quantidade",
            ),
        ),
    ]
