# Generated by Django 5.2.16 on 2026-07-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sessionrecord",
            new_name="history_ses_campaig_1a7d24_idx",
            old_name="history_ses_campaig_7214fe_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionrecord",
            new_name="history_ses_campaig_d85dc3_idx",
            old_name="history_ses_campaig_69944b_idx",
        ),
    ]
