# Generated by Django 5.2.16 on 2026-07-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("characters", "0001_initial"),
        ("encounters", "0001_initial"),
        ("enemies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("paused", "Pausado"),
                            ("finished", "Encerrado"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("free", "Livre"),
                            ("simple_order", "Ordem simples"),
                            ("initiative", "Iniciativa completa"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("track_player_resources", models.BooleanField(default=False)),
                ("round_number", models.PositiveIntegerField(default=1)),
                ("current_turn_index", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("master_notes", models.TextField(blank=True)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("victory", "Vitória"),
                            ("defeat", "Derrota"),
                            ("escape", "Fuga"),
                            ("negotiation", "Negociação"),
                            ("interrupted", "Interrompido"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("final_note", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combats",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combats",
                        to="encounters.encounter",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Combatant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "combatant_type",
                    models.CharField(
                        choices=[
                            ("enemy", "Inimigo"),
                            ("player", "Jogador"),
                            ("ally", "Aliado"),
                            ("neutral", "Neutro"),
                        ],
                        max_length=10,
                    ),
                ),
                ("display_name", models.CharField(max_length=150)),
                ("image", models.ImageField(blank=True, upload_to="combat/snapshots/")),
                ("max_hp", models.PositiveIntegerField(default=1)),
                ("current_hp", models.PositiveIntegerField(default=1)),
                ("max_power_points", models.PositiveIntegerField(default=0)),
                ("current_power_points", models.PositiveIntegerField(default=0)),
                ("armor_class", models.PositiveSmallIntegerField(default=10)),
                ("resistance_bonus", models.SmallIntegerField(default=0)),
                ("initiative", models.SmallIntegerField(blank=True, null=True)),
                ("turn_order", models.PositiveIntegerField(default=0)),
                (
                    "narrative_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal"),
                            ("wounded", "Ferido"),
                            ("badly_wounded", "Muito ferido"),
                            ("surrendered", "Rendido"),
                            ("fleeing", "Fugindo"),
                            ("unconscious", "Inconsciente"),
                            ("defeated", "Derrotado"),
                            ("special", "Especial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("custom_narrative_state", models.CharField(blank=True, max_length=80)),
                ("is_defeated", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_boss", models.BooleanField(default=False)),
                ("master_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combatants",
                        to="characters.character",
                    ),
                ),
                (
                    "combat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combatants",
                        to="combat.combat",
                    ),
                ),
                (
                    "enemy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combatants",
                        to="enemies.enemy",
                    ),
                ),
            ],
            options={
                "ordering": ("turn_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="CombatNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("note", "Observação"),
                            ("phase", "Mudança de fase"),
                            ("escape", "Fuga"),
                            ("surrender", "Rendição"),
                            ("reinforcement", "Reforço"),
                            ("objective", "Objetivo"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "combat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="combat.combat",
                    ),
                ),
                (
                    "combatant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="combat.combatant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HPChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_hp", models.PositiveIntegerField()),
                ("new_hp", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_reverted", models.BooleanField(default=False)),
                (
                    "combatant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hp_changes",
                        to="combat.combatant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="combat",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("encounter",),
                name="one_active_combat_per_encounter",
            ),
        ),
        migrations.AddConstraint(
            model_name="combat",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("campaign",),
                name="one_active_combat_per_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="combatant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("character__isnull", True), ("enemy__isnull", False)),
                    models.Q(("character__isnull", False), ("enemy__isnull", True)),
                    _connector="OR",
                ),
                name="combatant_exactly_one_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="combatant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_hp__gte", 0), ("current_hp__lte", models.F("max_hp"))
                ),
                name="combatant_hp_bounds",
            ),
        ),
    ]
